version: '3'
services:
  api:
    image: 'node:20-slim'
    container_name: 'api'
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3333:3333'
    command: 'npm run dev'
    depends_on:
      - cache
  cache:
    image: 'redis:alpine'
    container_name: 'redis_cache'
    ports:
      - '6379:6379'
    command: redis-server
    privileged: true
    volumes:
      - cache:/data

volumes:
  cache: 
    driver: local